# -*- coding: utf-8 -*-
"""Assignment-0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RNK2jGUHy45Bw0tkgn74kjZH3w2lFFI7
"""

#Registering new user in the file.
def register():
  s = input("Enter email ID: ")
  c = 0
  t = len(s)
  a = s.find('@')
  b = s.find('.')
  k = s[a:t]
  x = 0
  y = 0
  
  if '@' and '.' in k:
    c=c+1
    
  for i in range(a+1,b):
    x=x+1
    
  if x >= 4:
    c=c+1
  
  for i in range(0,a):
    if(s[i] =='.'):
      c=c+1
      break
  
  for i in range(0,a):
    if(s[i].isdigit()):
      c=c+1
      break
  
  if s[0].isalpha():
    c=c+1
  
  if c==3 or c==4:
    print("Email ID accepted!")
  else:
    print("Email ID invalid!")
  
  p = input("Enter Password: ")
  r = 0
  special_characters = "!@#$%^&*()-+?_=,<>/"
  
  if len(p)>=5 and len(p)<=16:
    r=r+1
  
  if any(i in special_characters for i in p):
    r=r+1
  
  for i in p:
    if i.isdigit():
      r=r+1
      break
  
  for i in p:
    if i.isupper():
      r=r+1
      break
  
  for i in p:
    if i.islower():
      r=r+1
      break
  if r==5:
    print("Password Accepted!")
  else:
    print("Password NOT ACCEPTED!!")
  
  if ((c==3) or (c==4)) and r==5:
    print("Successfully Registered!!")
  

  file_path = 'registrations.txt'
  with open(file_path, "a") as f:
    if ((c==3) or (c==4)) and r==5:
      f.write(s)
      f.write(" ")
      f.write(p)
      f.write('\n')

#When user chooses Forgot Password.
def forgot(g):
  with open("registrations.txt") as f:
    for line in f:
      h = line.split(" ")
      for i in h:
        if i == g:
          print("Password for",g, "is:",h[1])

#User chooses to LOGIN or REGISTER.
# 1 for Login 
# 2 for Register
enter = int(input("Login or Register?\n 1 for Login\n 2 for Register\n"))

#When user chooses to LOGIN.
if enter == 1:
  email = input("Email ID:")
  password = input("Password:")
  flag = 0
  with open('registrations.txt') as f:
    for line in f:
      u = line.split(" ")
      u[1] = u[1].replace('\n','')
      if email == u[0]:
        if password in u:
          print("Successfully logged in!!")
          flag=1
          break
        elif password not in u:
          print("Incorrect Password!!")
          f = input("Forgot Password?")
          if f == 'y' or f =='Y':
            forgot(email)
          else:
            flag=1
            break
          flag = 1

      elif email != u[0]:
        continue
    
    if flag==0:
      print("Email ID doesn't exist, please register!!")

#When user chooses to REGISTER.
elif enter == 2:
  register()